[package]
name = "kombi"
version = "0.1.0"
authors = ["Jess Schallenberg <jess.schallenberg@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A Parser Combinator Library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
